# This is the main configuration file of your application. It stores all the
# common options for every execution environment ('prod', 'dev', 'test').

# To avoid creating configuration files that are too long, we first import some
# files that define the values for important parts of the Symfony application,
# such as the security component and the dependency injection services
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# These are the configuration parameters that define the application's behavior
# and which are independent from the underlying technical infrastructure
# See http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl
    locale: en

# Basic configuration for the Symfony framework features
framework:
    # The 'ide' option turns all of the file paths in an exception page
    # into clickable links that open the given file using your favorite IDE.
    # Supported values are 'phpstorm', 'sublime', 'textmate', 'macvim' and 'emacs'.
    # When 'ide' is set to null the file is opened in your web browser.
    # See http://symfony.com/doc/current/reference/configuration/framework.html#ide
    ide: ~

    # When using the HTTP Cache, ESI allows to render page fragments separately
    # and with different cache configurations for each fragment
    # http://symfony.com/doc/current/book/http_cache.html#edge-side-includes
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "form/fields.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        # if you don't want to use SQLite, change the URL in parameters.yml or set the DATABASE_URL environment variable
        url: "%env(DATABASE_URL)%"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# Swiftmailer Configuration (used to send emails)
# instead of configuring the mailer credentials in this file, we pull
# them from the app/config/parameters.yml file. The reason is that config.yml
# stores options that change the application behavior and parameters.yml
# stores options that change from one server to another
#
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
